docker_compose('./docker-compose.yaml')

dc_resource('postgres')
dc_resource('db-init', resource_deps=['postgres'])
dc_resource('webserver', resource_deps=['db-init'])
dc_resource('scheduler', resource_deps=['db-init'])
dc_resource('triggerer', resource_deps=['db-init'])

sync_pyproj_toml = sync('../../../pyproject.toml', '/usr/local/airflow/blueprint/pyproject.toml')
sync_readme = sync('../../../README.md', '/usr/local/airflow/blueprint/README.md')
sync_src = sync('../../../blueprint', '/usr/local/airflow/blueprint/blueprint')
sync_shared_blueprints = sync('../../shared-blueprints', '/usr/local/airflow/shared-blueprints')

docker_build(
    'blueprint-advanced-airflow2',
    context='../../..',
    dockerfile='./Dockerfile',
    ignore=['.venv', '**/logs/**'],
    live_update=[
        sync_pyproj_toml,
        sync_src,
        sync_readme,
        sync_shared_blueprints,
        run(
            'cd /usr/local/airflow/blueprint && uv pip install -e .',
            trigger=['pyproject.toml']
        ),
        run(
            'cd /usr/local/airflow/shared-blueprints && uv pip install -e .',
            trigger=['../../shared-blueprints/pyproject.toml']
        ),
    ]
)
