"""Blueprint - Reusable task templates composed into Airflow DAGs via YAML."""

__version__ = "0.4.0"

from .builder import (
    Builder,
    DAGConfig,
    OnDagBuilt,
    StepConfig,
    build_all,
    build_all_airflow_dags,
    build_all_dags,
)
from .core import Blueprint, BlueprintDagArgs, DefaultDagArgs, TaskOrGroup
from .errors import (
    BlueprintError,
    BlueprintNotFoundError,
    CompositionDepthError,
    ConfigurationError,
    CyclicDependencyError,
    CyclicVariableError,
    DuplicateBlueprintError,
    DuplicateDAGIdError,
    IncompleteVariableError,
    InvalidDependencyError,
    InvalidVariableNameError,
    InvalidVariableValueError,
    InvalidVersionError,
    MultipleDagArgsError,
    NonContiguousVersionError,
    ProfileError,
    UndefinedVariableError,
    YAMLParseError,
)
from .errors import (
    ValidationError as BlueprintValidationError,
)
from .loaders import (
    discover_blueprints,
    get_blueprint_info,
    load_blueprint,
    validate_yaml,
)
from .models import (
    Any,
    BaseModel,
    ConfigDict,
    Dict,
    Field,
    List,
    Optional,
    Union,
    ValidationError,
    field_validator,
    model_validator,
)
from .registry import BlueprintRegistry, registry

__all__ = [
    "Any",
    "BaseModel",
    "Blueprint",
    "BlueprintDagArgs",
    "BlueprintError",
    "BlueprintNotFoundError",
    "BlueprintRegistry",
    "BlueprintValidationError",
    "Builder",
    "CompositionDepthError",
    "ConfigDict",
    "ConfigurationError",
    "CyclicDependencyError",
    "CyclicVariableError",
    "DAGConfig",
    "DefaultDagArgs",
    "Dict",
    "DuplicateBlueprintError",
    "DuplicateDAGIdError",
    "Field",
    "IncompleteVariableError",
    "InvalidDependencyError",
    "InvalidVariableNameError",
    "InvalidVariableValueError",
    "InvalidVersionError",
    "List",
    "MultipleDagArgsError",
    "NonContiguousVersionError",
    "OnDagBuilt",
    "Optional",
    "ProfileError",
    "StepConfig",
    "TaskOrGroup",
    "UndefinedVariableError",
    "Union",
    "ValidationError",
    "YAMLParseError",
    "build_all",
    "build_all_airflow_dags",
    "build_all_dags",
    "discover_blueprints",
    "field_validator",
    "get_blueprint_info",
    "load_blueprint",
    "model_validator",
    "registry",
    "validate_yaml",
]
