"""Loader with post-processing.

on_dag_built runs once per DAG, after every step has been wired up. It is the
layer for things that are not authoring decisions at all -- and the only place
that knows which file a DAG came from.
"""

import logging
from pathlib import Path

from airflow.models import DAG

from blueprint import build_all_airflow_dags

log = logging.getLogger(__name__)


def apply_platform_policy(dag: DAG, config_path: Path) -> None:
    """Stamp provenance, ownership and generated docs onto a finished DAG."""
    # render() never sees a path, so directory-derived policy has to happen
    # here. Each team owns a directory; that is where ownership comes from.
    team = config_path.parent.name
    source = config_path.name.removesuffix(".dag.yaml")

    dag.tags = [*(dag.tags or []), f"team:{team}", f"source:{source}"]

    # The tasks already exist, so ownership can be stamped onto them rather
    # than passed in as a default before they were built.
    for task in dag.tasks:
        task.owner = team

    task_ids = sorted(dag.task_ids)
    dag.doc_md = (
        f"Generated by Blueprint from `{config_path.name}`.\n\n"
        f"Owner: **{team}**. Raise issues with that team.\n\n"
        f"Tasks ({len(task_ids)}): {', '.join(f'`{t}`' for t in task_ids)}\n"
    )

    # Where an inventory push to a catalogue would go. The DAG is complete at
    # this point, so the record describes what was actually built.
    log.info(
        "dag_inventory dag_id=%s team=%s source=%s tasks=%d",
        dag.dag_id,
        team,
        config_path.name,
        len(task_ids),
    )


build_all_airflow_dags(on_dag_built=apply_platform_policy)
