"""Loader with post-processing.

BlueprintDagArgs covers settings DAG authors choose from. on_dag_built covers
settings they should not see at all.
"""

from pathlib import Path

from airflow.models import DAG

from blueprint import build_all_airflow_dags


def apply_platform_policy(dag: DAG, config_path: Path) -> None:
    """Runs once per DAG, after every step has been wired up."""
    # Provenance: which file produced this DAG. Useful when a DAG ID and a
    # filename have drifted apart. (.stem would leave a trailing ".dag".)
    source = config_path.name.removesuffix(".dag.yaml")
    dag.tags = [*(dag.tags or []), f"source:{source}"]

    # A uniform docs panel in the UI, without asking authors to write one.
    owner = (dag.default_args or {}).get("owner", "unknown")
    dag.doc_md = (
        f"Generated by Blueprint from `{config_path.name}`.\n\n"
        f"Owner: **{owner}**. Raise issues with that team.\n"
    )


build_all_airflow_dags(on_dag_built=apply_platform_policy)
